/**
 * Sprint 28 — Dutch UI copy for closed-beta consistency.
 * Keep provider/product names untranslated (Gmail, Outlook, Google Workspace, etc.).
 * Full NL/EN i18n framework ships in a later sprint; this module is the interim source of truth.
 */

export const navNl = [
  { to: "/dashboard", label: "Dashboard" },
  { to: "/opportunities", label: "Kansen" },
  { to: "/automations", label: "Automatiseringen" },
  { to: "/crm", label: "CRM" },
  { to: "/pipeline", label: "Pipeline" },
  { to: "/clients", label: "Klanten" },
  { to: "/projects", label: "Projecten" },
  { to: "/tasks", label: "Taken" },
  { to: "/ai-chat", label: "Copilot" },
  { to: "/ai-workspace", label: "AI-werkruimte" },
  { to: "/knowledge-brain", label: "Knowledge Brain" },
  { to: "/ai-agents", label: "AI-agents" },
  { to: "/proposals", label: "Offertes" },
  { to: "/contracts", label: "Contracten" },
  { to: "/invoices", label: "Facturen" },
  { to: "/documents", label: "Documenten" },
  { to: "/emails", label: "E-mails" },
  { to: "/inbox", label: "Inbox" },
  { to: "/integrations", label: "Integraties" },
  { to: "/analytics", label: "Analytics" },
  { to: "/settings", label: "Instellingen" },
];

export const emailsNl = {
  intro: "Beoordeel concepten, keur uitgaande mail goed en verstuur veilig.",
  help: "Versturen is uitgeschakeld tot e-mailverzending en organisatie-e-mailinstellingen aan staan. Goedkeuring kan vereist zijn vóór verzending.",
  provider: "Provider",
  sendingReady: "Verzenden gereed",
  sendingDisabled: "Verzenden uitgeschakeld",
  today: "Vandaag",
  compose: "Concept maken",
  tabs: {
    drafts: "Concepten",
    awaiting_approval: "Wacht op goedkeuring",
    scheduled: "Gepland",
    sent: "Verstuurd",
    failed: "Mislukt",
  },
  search: "Zoek onderwerp of ontvanger…",
  searchAria: "Zoek e-mails",
  blockedBanner:
    "Uitgaande e-mail is momenteel geblokkeerd. Configureer Instellingen → E-mail en schakel verzending in wanneer je klaar bent.",
  emptyTitle: "Nog geen e-mails",
  emptyBody: "Maak een concept of laat automatiseringen vervolgmails voorbereiden ter beoordeling.",
  headers: {
    recipient: "Ontvanger",
    subject: "Onderwerp",
    source: "Bron",
    status: "Status",
    creator: "Auteur",
    date: "Datum",
  },
  sources: {
    manual: "Handmatig",
    automation: "Automatisering",
    ai: "AI",
    inbox: "Inbox",
  },
  statuses: {
    draft: "Concept",
    pending_approval: "Wacht op goedkeuring",
    approved: "Goedgekeurd",
    scheduled: "Gepland",
    sending: "Bezig met verzenden",
    sent: "Verstuurd",
    failed: "Mislukt",
    needs_review: "Controle nodig",
    delivery_unknown: "Bezorging onbekend",
    cancelled: "Geannuleerd",
    rejected: "Afgewezen",
  },
  deliveryStatuses: {
    pending: "In afwachting",
    delivered: "Bezorgd",
    sent: "Verstuurd",
    failed: "Mislukt",
    bounced: "Teruggekaatst",
    unknown: "Onbekend",
  },
  historyKinds: {
    created: "Gemaakt",
    updated: "Bijgewerkt",
    submitted: "Ingediend",
    approved: "Goedgekeurd",
    rejected: "Afgewezen",
    sent: "Verstuurd",
    failed: "Mislukt",
    retried: "Opnieuw geprobeerd",
    cancelled: "Geannuleerd",
  },
  email: "E-mail",
  to: "Aan",
  cc: "Cc",
  subject: "Onderwerp",
  body: "Bericht",
  aiDraft: "AI-concept",
  saveDraft: "Concept opslaan",
  save: "Opslaan",
  improve: "AI verbeteren",
  submit: "Indienen ter goedkeuring",
  approve: "Goedkeuren",
  reject: "Afwijzen",
  send: "Versturen",
  sendGmail: "Versturen via Gmail",
  sendOutlook: "Versturen via Outlook",
  retry: "Opnieuw proberen",
  cancel: "Annuleren",
  confirmTitle: "Bevestig actie",
  confirmBack: "Terug",
  confirmOk: "Bevestigen",
  linkedInbox: "Gekoppelde inbox-conversatie",
  connected: "Verbonden",
  disconnected: "Verbroken — opnieuw verbinden vereist",
  source: "Bron",
  providerId: "Provider-ID",
  delivery: "Bezorging",
  noTextBody: "(geen tekstbericht)",
  failure: "Mislukt",
  mailbox: "Postvak",
  thread: "Conversatie",
  crm: "CRM",
  client: "klant",
  lead: "lead",
  providerReply: "Providerantwoord",
  connectedMailbox: "gekoppeld postvak",
  configuredProvider: "de geconfigureerde provider",
  reconnectWarning:
    "Verbind Google Workspace of Microsoft 365 opnieuw onder Integraties. Resend wordt niet gebruikt voor inbox-antwoorden.",
  providerDetails: "Providerdetails",
  sentVia: "Verstuurd via",
  providerMessageId: "Providerbericht-ID",
  internetMessageId: "Internetbericht-ID",
  originalAiSuggestion: "Originele AI-suggestie",
  history: "Geschiedenis",
  viewConversation: "Conversatie bekijken",
  recipientRequired: "Ontvanger is verplicht",
  subjectRequired: "Onderwerp is verplicht",
  loadFailed: "E-mails laden mislukt",
  sendBlockedToast: "Verzenden is uitgeschakeld. Concepten blijven beschikbaar.",
  confirmSendThreaded:
    "Dit antwoord wordt verstuurd via {provider} ({mailbox}). Resend wordt niet gebruikt voor inbox-antwoorden.",
  confirmSend: "Dit bericht wordt verstuurd via {provider}.",
  confirmGeneric: "Deze actie kan voor verzenden/annuleren niet ongedaan worden gemaakt. Doorgaan?",
  toasts: {
    aiDraftCreated: "AI-concept gemaakt",
    draftCreated: "Concept gemaakt",
    draftSaved: "Concept opgeslagen",
    submitted: "Ingediend ter goedkeuring",
    approved: "Goedgekeurd",
    rejected: "Afgewezen",
    sendCompleted: "Verzenden voltooid",
    cancelled: "Geannuleerd",
    retryCompleted: "Opnieuw proberen voltooid",
    aiRewriteApplied: "AI-herschrijving toegepast",
    done: "Klaar",
  },
};

export const inboxNl = {
  title: "Inbox",
  subtitle: "Gedeelde Gmail- en Outlook-conversaties",
  help: "Koppel Google of Microsoft onder Integraties en synchroniseer daarna. Antwoordconcepten gaan via E-mails ter goedkeuring — nooit automatisch verstuurd.",
  syncGmail: "Sync Gmail",
  syncOutlook: "Sync Outlook",
  views: "Weergaven",
  viewAll: "Alles",
  viewUnread: "Ongelezen",
  viewAssigned: "Aan mij toegewezen",
  viewLinked: "Gekoppeld",
  viewUnlinked: "Niet gekoppeld",
  provider: "Provider",
  all: "Alles",
  mailboxes: "Postvakken",
  noMailbox: "Nog geen postvak. Koppel eerst een mailbox onder Integraties.",
  noMailboxTitle: "Nog geen mailbox gekoppeld",
  noMailboxBody:
    "Inbox toont Gmail- en Outlook-conversaties na het koppelen van Google Workspace of Microsoft 365.",
  goIntegrations: "Naar Integraties",
  syncDisabledHint: "Koppel eerst de bijbehorende integratie om te synchroniseren.",
  emptyTitle: "Inbox is leeg",
  emptyBody: "Synchroniseer Gmail of Outlook nadat je Integraties hebt gekoppeld.",
  search: "Zoek onderwerp of deelnemer…",
  selectConversation: "Selecteer een conversatie",
  lastSync: "Laatste sync",
  syncNow: "Nu synchroniseren",
  adminOnlySync: "Alleen owners en admins kunnen postvakken synchroniseren",
};

export const analyticsNl = {
  emptyTitle: "Nog geen analytics",
  emptyBody:
    "Grafieken en KPI’s tonen alleen echte facturen, klanten en projecten — nullen betekenen dat er nog geen data is, geen kapot dashboard.",
  kpiPaid: "Totale omzet (betaald)",
  kpiInvoiced: "Totaal gefactureerd",
  kpiClients: "Klanten",
  kpiProjects: "Projecten",
  revenueTitle: "Omzet over tijd",
  revenueHelp: "Gefactureerd vs betaald per maand, op basis van je echte facturen.",
  revenueEmpty: "Nog geen factuurgegevens.",
  projectsTitle: "Projecten per status",
  projectsEmpty: "Nog geen projecten.",
  docsTitle: "Documentoutput",
  docsEmpty: "Nog geen documenten.",
  tasksTitle: "Taakvoltooiing",
  tasksEmpty: "Nog geen taken.",
  completed: "Voltooid",
  open: "Open",
  proposals: "Offertes",
  contracts: "Contracten",
  invoices: "Facturen",
  documents: "Documenten",
  projectStatus: {
    "In Progress": "In uitvoering",
    Review: "Review",
    Completed: "Voltooid",
    Blocked: "Geblokkeerd",
    Unknown: "Onbekend",
  },
};

export const integrationsNl = {
  title: "Integraties",
  subtitle: "Koppel Google, Microsoft, Slack, Discord, Zapier en webhooks.",
  help: "OAuth-refresh tokens worden versleuteld opgeslagen en nooit naar de browser gestuurd. Alleen owners en admins kunnen koppelen of ontkoppelen.",
  permissions: "Rechten",
  lastSync: "Laatste sync",
  health: "Status",
  account: "Account",
  connect: "Koppelen",
  disconnect: "Ontkoppelen",
  reconnect: "Opnieuw verbinden",
  refresh: "Vernieuwen",
  healthBtn: "Controleer status",
  adminOnly: "Alleen owners en admins kunnen integraties beheren",
  status: {
    connected: "Verbonden",
    disconnected: "Niet verbonden",
    error: "Fout",
    expired: "Verlopen",
  },
};

export const emptyNl = {
  clients: {
    title: "Nog geen klanten",
    description: "Voeg je eerste klant toe om projecten, offertes en communicatie op één plek te beheren.",
    why: "Klanten zijn de bedrijven en personen waarmee je werkt — gekoppeld aan projecten, taken en kansen.",
    action: "Klant toevoegen",
  },
  projects: {
    title: "Nog geen projecten",
    description: "Maak een project om klantwerk, taken en documenten overzichtelijk te houden.",
    why: "Projecten organiseren de levering voor een klant — plannen, taken, offertes en documenten horen hier.",
    action: "Project toevoegen",
  },
  tasks: {
    title: "Nog geen taken",
    description: "Leg vast wat er moet gebeuren, met deadline en prioriteit.",
    why: "Taken zijn de concrete volgende stappen op je projecten.",
    action: "Taak toevoegen",
  },
};

export function fmtNlDate(d) {
  if (!d) return "—";
  try {
    return new Date(d).toLocaleString("nl-NL", {
      day: "numeric",
      month: "short",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return "—";
  }
}
